export interface FiltroRegistrarUsuario {
    id:string,
    idRol:number,
    logUsuario:string,
    imagen:string,
    primerNombre:string,
    segundoNombre:string,
    primerApellido:string,
    segundoApellido:string,
    email:string,
    direccion:string,
    telefono:string,
    flgActivo:boolean,
    fechaRegistroCadena:string,
}
